### ISSUE TITLE
Makefile:30: *** recipe commences before first target.  Stop.

### ISSUE THREAD

**Issue by sci4me** [odin-lang/Odin#1087]
## Context

I just pulled and checked out the dev-2021-08 release. I am trying to run `make` but getting this failure.

* Operating System: 5.11.8-arch1-1
* Please paste `odin version` output: n/a

## Expected Behavior

The makefile should run as normal and build Odin and the demo.

## Current Behavior

I am getting this when I run `make` or `make all`:
```
Makefile:30: *** recipe commences before first target.  Stop.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Check out dev-2021-08
2. Run `make`

---

Not sure if I'm just doing something stupid here... probably?

**Comment by graphitemaster** [comment]
The problem is the Makefile's use of `$(error "Requirement: llvm-config must be version 11")` which does not work on Linux at all, that triggers that specific error. In general.

Archlinux ships with llvm12 in it's repos, which is not compatible here, it has an llvm11 package but installing it will cause a clang downgrade and other package downgrades that depend on it and clang.

Right now your best best to building for Linux is to download a separate llvm11 package from
https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10.tar.xz

Then extract it into an `llvm` folder in the root of Odin, comment out the LLVM version detection code and modify your Makefile to read this instead
```
# ifeq ($(OS), Darwin)
# 	LLVM_CONFIG=llvm-config
# 	ifneq ($(shell llvm-config --version | grep '^11\.'),)
# 		LLVM_CONFIG=llvm-config
# 	else
# 		$(error "Requirement: llvm-config must be version 11")
# 	endif
# 
# 	LDFLAGS:=$(LDFLAGS) -liconv
# 	CFLAGS:=$(CFLAGS) $(shell $(LLVM_CONFIG) --cxxflags --ldflags)
# 	LDFLAGS:=$(LDFLAGS) -lLLVM-C
# endif
# ifeq ($(OS), Linux)
# 	LLVM_CONFIG=llvm-config-11
# 	ifneq ($(shell which llvm-config-11 2>/dev/null),)
# 		LLVM_CONFIG=llvm-config-11
# 	else
# 		ifneq ($(shell llvm-config --version | grep '^11\.'),)
# 			LLVM_CONFIG=llvm-config
# 		else
# 			$(error "Requirement: llvm-config must be version 11")
# 		endif
# 	endif
# 
# 	CFLAGS:=$(CFLAGS) $(shell $(LLVM_CONFIG) --cxxflags --ldflags)
# 	LDFLAGS:=$(LDFLAGS) $(shell $(LLVM_CONFIG) --libs core native --system-libs)
# endif

CFLAGS:=$(CFLAGS) $(shell ./llvm/bin/llvm-config --cxxflags)
LDFLAGS:=$(LDFLAGS) $(shell ./llvm/bin/llvm-config --libs --ldflags) -lz -ltinfo
```

This will build a stand-alone Odin which does not depend on system LLVM at all.

**Comment by sci4me** [comment]
Ah, I had forgotten about the llvm12 issue. I will try your suggestions after work today and report back.

**Comment by sci4me** [comment]
Sorry for the delay, but, good news: that worked. Thank you!
