### ISSUE TITLE
What to do about AV false positives?

### ISSUE THREAD

**Issue by SystematicLoop** [odin-lang/Odin#1513]
## Context

odin version dev-2022-02-nightly:a04d849e
Odin: dev-2022-02-nightly:a04d849e
        OS:   Windows 10 Home Basic (version: 20H2), build 19042.1526
        CPU:  Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
        RAM:  32725 MiB

## Unexpected Behavior

I compiled a basic hello world program and a trojan had embedded itself in the executable. The trojan's name was "Sabsik.TE.A!ml". I am unsure if it came from the compiler but this happened immediately after compiling.

**Comment by SystematicLoop** [comment]
So I've been digging around. I can confirm multiple compilations produces this trojan threat.

````
package main

import "core:fmt"
import "core:io"
import "core:os"

main :: proc() {
    x := 2;
    y := 3;
    z := x + y;

    fmt.println(x, "+", y, "=", z);

    file, error := os.open("hello_world.odin");
    data, success := os.read_entire_file_from_handle(file);
    os.close(file);

    fmt.println(success);
    fmt.println(cast(string) data);
}
```
This is the program that compiles with a trojan. However, when I remove the calls to the os package, the trojan disappears from the executable.

**Comment by Kelimion** [comment]
Hi,

Seeing as you continued to use the compiler and tried to narrow down the problem, I take it you understand that this is - of course - a false positive. It doesn't actually compile with a trojan.

I compiled the example you gave and uploaded it to [VirusTotal](https://www.virustotal.com/gui/file/c07ee3a33a62ef58717b8adcc137d47b9f9d5583ae5f959b80abac9377b7ab6f/detection). Unsurprisingly it's clean. And given the report you made, equally unsurprisingly, 1 out of 67 tests ran thought there was something wrong with it.

That's just a shoddy definition by that particular AV vendor. The same false positive has also been seen coming from [MSVC compiling a C program](https://answers.microsoft.com/en-us/protect/forum/all/false-positive-win32sabsikftaml/5aa91237-fb7f-4dff-a868-09737cc2bfca), from wrapping an executable in [Steam DRM](https://steamcommunity.com/discussions/forum/0/3165461775594224582/) and countless others. As noted, the `!ml` suffix means that machine learning was used, which likely contributed to it being an obvious false positive.

I changed the Issue's topic so as not to prejudice this fine software project with a prejudicial headliner over what's essentially a nothing burger that has nothing to do with us.

There isn't a whole lot we can do for you on this because the compiler not a threat in any way, nor does it contain one. The only advice I can give you is that given in the MSVC case I linked to, and that's to update your Windows (Defender) or whatever AV program gave you this misleading result. You can also upload the file you compiled to VirusTotal to verify for yourself that it's just the AV playing silly buggers and it should go for remedial training (update its definitions of what is and isn't a threat) instead of alarming people.

I hope this helps.
