### ISSUE TITLE
Allow overloading of procedures in different scopes (e.g: `len`, `reserve`, `append`)

### ISSUE THREAD

**Issue by Tetralux** [odin-lang/Odin#152]
Ref https://github.com/gingerBill/Odin/issues/148.

A.odin:
```go
S1 :: struct {}
len :: proc(s: S1) -> int {
        // Determine length of an S1...
        return 1;
}
```
B.odin:
```go

S2 :: struct {}
len :: proc(s: S2) -> int {
        // Determine length of an S2...
        return 2;
}
```
main.odin:
```go
using import "A.odin";
using import "B.odin";

main :: proc() {
	s1: S1;
	s2: S2;
	a := make([]int, 3);

	i := A.len(s1);
	j := B.len(s2);
	k := len(a); // Error
	// What benefit do these qualifications grant you
	// that is better than having them be overloads?
	// i.e:
	// i := len(s1);
	// j := len(s2);
        // k := len(a);

	assert(i == 1);
	assert(j == 2);
	assert(k == 3);
}
```

**Comment by gingerBill** [comment]
Overloading and scopes don't mix well. This is why I have restricting overloading to a single "level". In languages such as C++, functions can only be defined at the global scope and thus, overloading only works there. However, Odin has many different forces of scopes: universal, global, file, procedure, etc and because of this, procedures can be nested within other procedures.

This was one of the main reasons as to why I didn't want procedure overloading in the first place as it does work well in a language such as Odin.

I recommend that you name the procedure specifically for their use cases rather than use `len` for everything.
