### ISSUE TITLE
Conditional `import` statements are always run

### ISSUE THREAD

**Issue by JimmyLefevre** [odin-lang/Odin#1558]
```
package main

when ODIN_OS == .JS {
  import "vendor:wasm/WebGL"
} else when ODIN_OS == .Linux {
  import "vendor: OpenGL"
} else {
  #panic("Unsupported OS")
}

main :: proc() {}
```

## Expected Behavior

`odin build . -target=js_wasm32` should import the `vendor:wasm/WebGL` library, but not the `vendor:OpenGL` library.
Similarly, `odin build . -target=linux_amd64` should import `vendor:OpenGL`, but not `vendor:wasm/WebGL`.

## Current Behavior

Currently, both builds fail by trying to import the wrong GL library alongside the correct one. (Building for `js_wasm32` gives a `Compile time panic: package os does not support a js target` error, and building for `linux_amd64` gives an `Undeclared name: webgl` error, among others.)

## Failure Information (for bugs)

When adding `#panic`s to both cases, only the correct one is triggered, i.e.

```
when ODIN_OS == .JS {
  #panic("JS")
  import "vendor:wasm/WebGL"
} else when ODIN_OS == .Linux {
  #panic("Linux")
  import "vendor: OpenGL"
} else {
  #panic("Unsupported OS")
}
```

will correctly display "JS" for the `js_wam32` build, and "Linux" for the `linux_amd64` build. It seems like the error is specific to `import` statements?

**Comment by gingerBill** [comment]
There are two things to note here:

1. WebGL and OpenGL do NOT have the same interface thus doing this won't be a good idea expecting to use them interchangeably.
2. This is not a bug and imports will always be checked regarding of whether they are in a `when` statement or not.

(1) is done because WebGL doesn't have to imitate the C stuff and it is much closer to what Odin does with slices because of the calling conventions. You could wrap WebGL to mimic OpenGL but it would not really be beneficial.

(2) is a little more complicated and is partially related to the technical reason of preventing cyclic imports. But in short, this is not a bug. If you want platform specific code like that, I recommend either doing something like `foo_linux.odin` or `bar_windows_amd64.odin`, or doing the following:

```odin
//+build windows
package foo

...
```

**Comment by skoobiii** [comment]
#1558
