### ISSUE TITLE
Proc Calls at File Scope

### ISSUE THREAD

**Issue by bpunsky** [odin-lang/Odin#194]
```_ :: compiler_assert(false, "No freetype libraries specified for this platform.");```
from Birk's issue

This is such a grungy hack. And it doesn't work if the proc doesn't have return values. We can already do it anyway, so for the love of sweet consistency, could we get file-scope proc calls?

(I promise not to abuse them)

(much 😛)

**Comment by gingerBill** [comment]
The issue here is calling procedures at file scope without declaring to a variable is extremely dodgy. It might be better to have `assert` be a built-in procedure instead of a user-level one and then have something like `#assert(cond)` for `compile_assert` so that the parser knows that this is special.

**Comment by bpunsky** [comment]
It doesn't seem especially sketchy to me to have the file scope essentially be `main`, like Python or something, but I imagine it does to you 😛

**Comment by Tetralux** [comment]
Makes sense to me if proc calls at file scope are run before `main`.
