### ISSUE TITLE
Silent compiler crash

### ISSUE THREAD

**Issue by sigmawq** [odin-lang/Odin#2177]
## Context

Compiler crashes silently when trying to compile the code below:
```
package main

import "core:fmt"

Distribution_Option :: struct($Data: typeid) {
	data: Data,
	available: f64,
}

Element_Type :: enum u8 {
	A, B, C
}

Element :: struct {
	type: Element_Type, 
	quanity: i32,
	need: ^Bav,
}

Bav :: struct {
	a: int,
}

Baz :: i16
Bar :: struct {
	element: Element,
	need: ^Bav,
}

Foo :: struct {
	container: [dynamic]Bar,	
}

main :: proc() {
	Option :: Distribution_Option(^Foo)
	options: [dynamic]Option
	another_container: [dynamic]Foo
	append(&another_container, Foo{})
	for record in &another_container {
		acc := 0

		for thing in &record.container {
			acc += int(thing.element.quanity)
		}

		append(&options, Option {})
	}

	fmt.println("finished")
}
```
```
Odin: dev-2022-11-nightly:382bd876
OS:   Windows 10 Home Basic (version: 21H2), build 19044.2130
CPU:  Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
RAM:  16325 MiB
```
## Expected Behavior
Program should compile with no crashes.

## Current Behavior
Compiler crashes silently (sometimes, compile rate on my project is much lower than in this stripped example). 
Also from time to time I get the following message on crash:
```
LLVM Error:
All nodes should be resolved!
!3032 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64, align: 64, dwarfAddressSpace: 0)
```

### Steps to Reproduce
1. Run `odin build -debug` until you hit the crash (it takes 5 to 10 attempts to get the crash on average on my machine)

**Comment by Kelimion** [comment]
This is peculiar. I compiled and ran it 10 times in a row. 10 times in a row it printed `finished`. I tried it 10x each with and without `-debug`.

**Comment by awwdev** [comment]
I still think we should make a notice about the broken state of `-debug` and save people from pain. Especially since it's unkown when it's going to be fixed (seems like it depends solely on an external intervention (some person who wants to fix debug for Odin) and who knows when that will occur and how well). So we eventually save a lot of people from vanishing into a rabbit hole of compiler crashes and even wrongly compiled code (so you get weird runtime errors). 
People may think Odin is very broken based on their experience with `-debug`. But Odin is very robust otherwise. 
It perhaps also reduces the Issue count, we have quite a bit of Issues about `-debug`. 
Me (and I guess many other long-term users) are longing for `-debug` to work correctly and are happy for any updates on the matter.
