### ISSUE TITLE
optnone procedures do not get noinline attribute

### ISSUE THREAD

**Issue by jon-lipstate** [odin-lang/Odin#2179]
## Context
```
LLVM Error:
Attribute 'optnone' requires 'noinline'!
void (%handmade.Loaded_Bitmap*, i64, i64, i64, [4 x float]*, %handmade.Loaded_Bitmap*, float, i8*)* @handmade.draw_rectangle_quickly
```
i can make the llvm error go away by commenting out the opt mode
// @(optimization_mode = "minimal")
draw_rectangle_quickly :: proc(

Per discussion with gingerBill & Jesse:
`Odin should ensure that optnone procedures also get noinline attribute tags assigned to them.`

**Comment by JesseRMeyer** [comment]
Looks like this is fixed by adding `lb_add_attribute_to_proc(m, p->value, "noinline");` to the `ProcedureOptimizationMode_Minimal` switch case in llvm_backend_proc.cpp.  This resolved the issue locally.

The front end already catches the combined use of #force_inline with @(optimization_mode = "minimal") case, but we didn't catch the broader case of building the entire project with o:speed (which will cause LLVM to determine inline fitness) but still specifying a procedure's opt mode as minimal.
