### ISSUE TITLE
Make array copyable?

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2183]
Could we make it possible to copy a dynamic array?
I think it is possible with slices, but it can't find anything on dynamic arrays.

So something like this:
my_new_array : [dynamic]int;
my_new_array = copy(my_old_array);

Thanks!

**Comment by Kelimion** [comment]
We could conceivably add a `clone_dynamic_array` to `core:mem` as a companian to `clone_slice`, if that is what you mean.

**Comment by xzores** [comment]
I am very new to Odin and find the documentation to be very limited. I think that coping an array is something we do a lot. So i am confused why it is not a default thing, why is this hard? So I don't think having a "clone_dynamic_array " function hidden in some file i need to import a useful feature.
Or if so then it should be written in some documentation.

**Comment by Kelimion** [comment]
There is no built-in `copy` for dynamic arrays because nobody has run into a need for it before.
Now you are right that it's not uncommon to want to clone one array to another.
```odin
// This is what you want to copy
source := make([dynamic]int, 100)

// This is the destination
destination := make([dynamic]int, len(source))

// Use the slice operator [:] to treat a dynamic array as a slice, copy slice contents across
copy(destination[:], source[:])
```
This is why there's no `copy` variant that supports a dynamic array, we have `[:]`.

What you're asking for is a `clone` operation, i.e. one that allocates the destination for you *and* copies. We like to be explicit about things in Odin so there are no hidden costs when you read the source.

**Comment by xzores** [comment]
ok, I see this 
copy(destination[:], source[:])
is what it was looking for.

**Comment by xzores** [comment]
Why is this so convoluted though? could it not just be:
copy(destination, source)

**Comment by xzores** [comment]
Also the following:
copy(destination[:], source[:])

does not work on SOA arrays.

**Comment by Kelimion** [comment]
> Why is this so convoluted though? could it not just be: copy(&destination, &source)

As I have explained above, you're asking for something called `copy` to allocate if necessary. That is a distinct operation. Not just something, but a built-in command, which is expected to have certain semantics.

The built-in copy expects the destination buffer to exist and be sized accordingly. If we alter it to take a dynamic array as its destination, it's going to do one of two things differently:
- It'll resize the dynamic array to fit the source data, if needed
- Like the slice variant, it'll copy the amount that'll fit in the result. Which if an empty dynamic array, means zero items.

The semantics are not equivalent.

**Comment by xzores** [comment]
Ok, I see, yeah, I thought that it would resize it, but yeah.
I have not thought about this much, but it was baited by the fact that there were no sizes.
Maybe something could be done here? I am not sure what but, for a newbie, it is a little misleading.

Thanks for the answers, I will close the issue.

**Comment by Kelimion** [comment]
As the implementation of `copy` above shows, the size to copy is automatically determined to be the maximum amount that'll fit in the destination. The reason that `copy` can do that is because a slice `[]` carries with it its length (number of items) and the type, which tells us the size of the element type. Together this gives us the copy size.

Which is to say that:
```odin
source := make([]int, 100) // 100 items to copy
dest := make([]int, 42) // but we only have room for 42
copy(dest, source) // will copy 42 items without writing past the end of the destination
```

If you wanted to copy less than the full source array to the destination, you can do this:
```odin
source := make([]int, 100) // 100 items to copy
dest := make([]int, 100) // 100 items in destination
copy(dest, source[:42]) // will copy first 42 items to the beginning of the destination array
copy(dest[42:], source[50:]) // will copy the remaining items starting 50 items into the source *after* the previous 42 items.
```
