### ISSUE TITLE
Allow concat 2 non-const strings?

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2184]
How can I concat 2 non-const strings?
Do I really have to make a string builder?

And if so would this really be the best way?
a : strings.Builder = builder_none();
write_string(&a, "This is my string: ");
write_string(&a,  My_other_non_const_string);

And how would i get a string from this?

Would i do this:
clone_from_bytes(a.buf[:])?

Why not allow  me just to do this: 
"This is my string: " + My_other_non_const_string

**Comment by Kelimion** [comment]
One way:
```odin
a: strings.Builder
write_string(&a, "This is my string: ")
write_string(&a, My_other_non_const_string)
result := strings.to_string(a)
```
Another way:
```odin
buf := make([]u8, 500)
a := "This is my string: "
copy(buf, a)
copy(buf[len(a):], b)
result := string(buf[:len(a) + len(b))
```
And there are other ways besides.

As for why not `str := "This is my string: " + My_other_non_const_string`. Because that is a monumentally bad idea.
Not only does `+` now mean more than 1 thing, it's now not just a concatenation instead of addition, it also makes an allocation for you.

Odin is a low-level language, not Python. Programs are more maintainable and understandable when the code does what you write, not a whole bunch in addition implicitly.

This explicitness (for sanity's sake) doesn't even inflate the line count compared to other low-level languages. A program ported to Odin from C often results in a third the number of lines.

**Comment by xzores** [comment]
Thanks you guys!
