### ISSUE TITLE
Deleting a silent allocated slice crashes in release mode

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2366]
I am running dev-2023-02-nightly:fcc920ed

When I have a function like the following:
```
source_pos_voltage_coe :: proc(parent : any, cur_time : f64, delta_time : f64) -> h.Model_step_result {
        c : ^Source = transmute(^Source)parent.data;
        c.value = c.driver.driver_function(&c.driver, cur_time);
        
        return {c.value, {}, {-1}};
}

```
I crash on the deletion of the slice.
```
Model_step_result :: struct {
	offset : f64,
	cur_coefficients : []f64,
	volt_coefficients : []f64,
}
```

If I change it to a dynamic array, it seems to work fine.
```
Model_step_result :: struct {
	offset : f64,
	cur_coefficients : [dynamic]f64,
	volt_coefficients : [dynamic]f64,
}
```

I assume it is because of the returned value being empty. Is this how it should work.

Also it works fine in debug.

**Comment by gingerBill** [comment]
That's because the slice will be allocated with the stack frame's memory. You'll need to do something like `slice.clone` or `make` to make it go beyond the stack frame.

**Comment by xzores** [comment]
But is that the case for dynamic arrays as well?

**Comment by gingerBill** [comment]
Nope. Dynamic array literals (which can be disabled with `-no-dynamic-literals` are kind of anti-feature of Odin since they will allocate using the `context.allocator` as backing rather than stack memory.

**Comment by xzores** [comment]
That to me seems odd, but ok

**Comment by SentientCoffee** [comment]
With your current solution, you are effectively doing this:
```odin
source_pos_voltage_coe :: proc(parent : any, cur_time : f64, delta_time : f64) -> h.Model_step_result {
        c : ^Source = transmute(^Source)parent.data;
        c.value = c.driver.driver_function(&c.driver, cur_time);
        
        // Stack allocated arrays
        cur_coeff  := [?]f64{}
        volt_coeff := [?]f64{-1}

        return {c.value, cur_coeff[:], volt_coeff[:]};
}
```
The stack allocated arrays here will go out of scope once you return from the function, and the slices that hold pointers to them will become invalid.

With the dynamic arrays, you are doing this:
```odin
source_pos_voltage_coe :: proc(parent : any, cur_time : f64, delta_time : f64) -> h.Model_step_result {
        c : ^Source = transmute(^Source)parent.data;
        c.value = c.driver.driver_function(&c.driver, cur_time);
        
        // _Dynamic_ arrays literals, meaning they will allocate on creation, extending the lifetime
        // This is equivalent to making a new dynamic array and then `append`ing the values in the literal
        // This can be made an error with `-no-dynamic-literals` at build time
        cur_coeff  := [dynamic]f64{}
        volt_coeff := [dynamic]f64{-1}

        return {c.value, cur_coeff, volt_coeff};
}
```
Dynamic arrays have a reference to their data on the "heap" (or wherever your `context.allocator` is allocating memory), so when you make them you hold on to the data inside `Model_step_result`, rather than on the stack like in the former version. Dynamic arrays also hold the allocator used to append elements to them so they can be deleted properly, unlike slices which only hold a pointer to the data and the length.
