### ISSUE TITLE
odin check reports errors in subfolders of same project (with same package name)

### ISSUE THREAD

**Issue by jon-lipstate** [odin-lang/Odin#2372]
## Context

Issue was found due to `ols` traversing the directory structure (as i understand it) and calling `odin check` in each subfolder. because `odin check` is called from a subfolder, it doesn't see the parent folders scope (which can see the types all align). `odin build` fine (when called from the parent dir). 

I think the guard for this is to test if the parent folder has odin files, and if they're the same package.

## Sample Repro
```odin
// in ./_main.odin
package scratch
main::proc(){}
Foo::struct{ A:u8,}
// in ./bar/baz.odin
package scratch
Foobar:: struct {f:Foo}
// call odin check . from ./bar/ as cwd
```

**Comment by jon-lipstate** [comment]
@Kelimion When building, Odin sees this as acceptable (because it is traversing downwards). When checking, it does not. The incongruency between build & check is the root of my comment.

**Comment by Kelimion** [comment]
Of course building `_main.odin`  will succeed without error. In your reproduction sample, it doesn't import `bar` and doesn't rely on anything in `bar/baz.odin`. Because it doesn't import `bar`, it won't typo-check it.

Conversely, `bar/baz.odin` references a type `Foo` that's defined in `_main.odin` in the parent directory, but it doesn't actually import it, so it's small wonder that it won't know what `Foo` is. Again, not a bug.

A package consists of files in the same directory with the same `package name` at the top. If they exist in different directories, they're different packages. Odin has not ever considered files in a parent or child directory as part of a project if they were not explicitly imported.

I'm not sure what you think the bug here is, because there is none. It may be considered a bug in OLS for it to call `odin check` on a package when it should call it on the main package itself, but if - as in this example you gave - you don't actually import the sub-directory package, how would `odin check`  or OLS know about it?

**Comment by krixano** [comment]
Yeah, running `odin check` from `./bar/` cannot see `Foo` because the parent directory is considered a separate package, so it would need to be imported with `import "../"`. When you run `odin build .` in the parent directory, it doesn't need the `./bar/` package to compile, since it doesn't rely on anything in that package, so that's why it succeeds.

As for OLS checking subdirectories even when they are not imported - all I will say is generally you want a text editor to check *all* of your code, including unused code, not just the code you import.

**Comment by jon-lipstate** [comment]
ahh i stand corrected. i was convinced build and check were not aligned (eg build was more permissive than check).

It is as you say, i had not yet used it that it had not materialized. 

if i modify main i get the build error... I retract my concern entirely
```odin
main :: proc() {
	fb := Foobar{{0x42}}
}
```
```shell
C:/_repos/odin/scratch/_main.odin(3:8) Error: Undeclared name: Foobar
        fb := Foobar{{0x42}}
              ^~~~~^
```
