### ISSUE TITLE
Reduce number of range and slice operators

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#239]
Current:
```
x[a..b] // half-closed
x[a...b-1] // open
for i in 0..N {} // half-closed
for i in 0...N-1 {} // open
switch x {
case a..b: // half-closed
case x...y: // open
}
```

Proposed:
```
x[a:b] // half-closed
for i in 0..N-1{} // open
switch x {
case x..y: // open
}
```

Rationale: removes confusion between `..` and `...` and adds familiarity for slicing from languages such as Python and Go.

**Comment by Tetralux** [comment]
This strikes me as a good idea, despite having two very different operators
for similar things.

The familiarity from slicing languages is a decent idea; the difference
will be easier to remember and work with because of the Python/Go reference
- at least for polyglots.

If you're a C-only programmer, then it won't be so obvious, but still.
In my experience, the open range is normally what you want, and is clearer
because of the explicit N-1, so I'd personally prefer that to be `..`.

With this change, both operators are short to type... Three dots always
felt a bit much to me.
