### ISSUE TITLE
Weird feature interaction between named return values and defer statements

### ISSUE THREAD

**Issue by gabriel-domingues** [odin-lang/Odin#2505]
## Context

This may be be documented somewhere, but mutation of named return values on defer statement seems to happen (one can print in the defer block to see it runs), but have no effect on the return value.

## Minimal Example:

```
package main
import "core:fmt"                                                                                                                             main :: proc() {
        n := fn()
        fmt.printf("%d\n", n)
}

fn :: proc() -> (delta: uint) {
        delta = 0
        defer delta += 1
        return
}
```

## Expected Behavior

Expected to return `1`

## Current Behavior

Got `0`

## Discussion

There is a similar situation on the `or_return_operator` in the demo. However, the `defer if` case does not happen, so it is not tested. I am running on the latest release `dev-2023-04`.

**Comment by elusivePorpoise** [comment]
This is the intended behavior. You cannot change the return values after a `return`; although you can use the named return variables in a post-return defer, the return value(s) is/are copied and effectively "locked in" at the point of the `return` statement.

That `defer if` example in the demo probably should be changed..

**Comment by SaculRennorb** [comment]
Just to maybe incentivize changing the example: I was just confused by the same problem, looked at the documentation to find the same example, and then got further confused by order of operations during return from a function:  

https://discord.com/channels/568138951836172421/568871298428698645/1343762468886941738  

I think changing the docs here (https://odin-lang.org/docs/overview/#or_return-operator) (the `defer if err != nil {` block) would be good to at least not seemingly confirm that return values can be changed in defer blocks, especially since the modified values in that example inst even used for anything (by defers evaluated later - which is the only way to make use of such a modified return values)

**Comment by haesbaert** [comment]
> This is the intended behavior. You cannot change the return values after a `return`; although you can use the named return variables in a post-return defer, the return value(s) is/are copied and effectively "locked in" at the point of the `return` statement.
> 
> That `defer if` example in the demo probably should be changed..

Just here to say that I also got bitten by the demo example.
