### ISSUE TITLE
Files with build tags are still checked when targeting excluded platforms

### ISSUE THREAD

**Issue by Caedo** [odin-lang/Odin#2707]
## Context

Files that contains build tags are semantically checked even when targeting platform, that were excluded by that tag. 
For example, importing any vendor library, that's not supported on wasm targets, in file with build tag `//+build windows` will cause compilation errors. That's different behaviour to file suffixes that works as expected

* Operating System & Odin Version:
        Odin: dev-2023-08:12b7df55
        OS:   Windows 10 Home Basic (version: 22H2), build 19045.3208
        CPU:  AMD Ryzen 7 3700X 8-Core Processor
        RAM:  32720 MiB

## Expected Behavior

Files shouldn't be evaluated on platforms excluded by build tag

## Current Behavior

Files are evaluated on platforms excluded by build tag

### Steps to Reproduce

1. Create two files, one with build tag `//+build linux` for example,
2. Add to file with build tag whatever text that shouldn't compile,
3. Build the project with Windows as a target,
4. Compilation fails
5. Change name of the file to contain `_linux` suffix
6. Compilation pass

**Comment by gingerBill** [comment]
Can you show me the file you are using?

Build tags must be attached to the package declaration itself

```odin
//+build linux
package name
```

There cannot be a newline between the comment and the package declaration.

**Comment by Caedo** [comment]
The files I was using for tests were:
```odin
package main

import "core:fmt"

main :: proc() {
    fmt.println(ODIN_OS)
}
```
and:
```odin
//+build linux

package main

slkdfjslkdj
```
So I had a newline after the tag. When deleting it it works as expected.
It probably needs to be s warning, or compiler error, because it's pretty easy to make mistake, and also it's not mentioned in the Overview.

**Comment by gingerBill** [comment]
@Caedo It cannot be a warning nor error because it could be a valid comment used in documentation, as annoying as that is.

**Comment by Caedo** [comment]
Other suggestion would be to allow having whitespaces between tag and `package` but I guess there is a reason why that's not allowed.

Anyway, if that's all allowed the issue can probably be closed

**Comment by gingerBill** [comment]
The gap exists because of the documentation generator. If a comment is not attached to a declaration, it is not included, and that tag system works exactly the same. The only way to know if a tag is actually used or if it is a general comment is to attach it to something.

**Comment by Caedo** [comment]
Then maybe making it its own language construct, instead of a comment would be better?

**Comment by leidegre** [comment]
If I may,

Is it likely that a comment `//+build linux` not immediately followed by a package is intentional? If it is then producing a warning would be warranted. Build tags are slightly awkward in that there's no whitespace between `//` and `+build` this makes them stand out.

This does not have to be implemented in the compiler directly, it could be implemented in a tool like `odin vet`

**Comment by leidegre** [comment]
> Build tags are slightly awkward in that there's no whitespace between `//` and `+build` this makes them stand out.

So, this might have been a mistake on my part, I just assumed that this was the case from browsing the Odin core package where this was the case sometimes but I see now that it isn't consistent.

For reference, I use the Go documentation since this is where I first learned about this. I think build tags is a great idea and feature and I'm not trying to say that everything needs to work the same.

https://pkg.go.dev/cmd/go#hdr-Build_constraints

**Comment by karl-zylinski** [comment]
Is this fixed now that we have `#+build` tags that can have linebreaks between them and the package line?
