### ISSUE TITLE
Compiling with -o:speed results in silent crash.

### ISSUE THREAD

**Issue by xzores** [odin-lang/Odin#2881]
## Context

I can compile my program with `odin run .`, but adding -o:speed, so that it becomes `odin run . -o:speed` results in a silent crash with no output. (It is the same with `odin build . -o:speed`)

 Odin: dev-2023-10-nightly:2cca0050
        OS:   Windows 11 Home Basic (version: 22H2), build 22621.2428
        CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
        RAM:  32507 MiB

## Expected Behavior

It should compile or give an error

## Current Behavior

A silent crash, there is no exe outputtet.

### Steps to Reproduce

I have no idea. I would like to hear if anyone has a similar issue, if not I will make my project public.

**Comment by laytan** [comment]
This also happens on Linux and Darwin with LLVM 17 when using RTTI (like reflection)

**Comment by JesseRMeyer** [comment]
There are known crashes and other issues with LLVM 17 support.  However, do try to provide a minimum source repo because otherwise we can only speculate on what's happening.

There is 1 known case of a silent crashes with LLVM 17 w/ optimizations, and it comes when LLVM tries to perform a constant fold optimization recursively, but unbounded, causing a stack overflow.  Unclear if it's genuinely bad IR on Odin's side, but in any case, it's something we have to address.

Separately, there's a known problem with the typeid system and LLVM's new type system.

**Comment by laytan** [comment]
Should be fixed now, @xzores can you try on the latest master commit and close if it is fixed?
