### ISSUE TITLE
Using a nil pointer struct crashes silently

### ISSUE THREAD

**Issue by keenfoong** [odin-lang/Odin#2963]
## Context
Using a nil pointer to a struct does a silent crash.

* Operating System & Odin Version: 
        Odin: dev-2023-11-nightly:04244041
        OS:   Windows 10 Home Basic (version: 22H2), build 19045.3693
        CPU:  AMD Ryzen 9 3900X 12-Core Processor
        RAM:  32714 MiB

Tested the nightly version after getting no error in the stable version either.

## Expected Behavior

An error saying cannot use a nil pointer, or something to that effect.

## Current Behavior

Nothing happens, silently crashes with no indication.

### Steps to Reproduce

Basic Repro:
```odin
package main

import "core:fmt"

Ent :: struct {
    components: map[int]string,
}

main :: proc() {
    ent: ^Ent = nil
    ent.components[5] = "hello"
    fmt.println(ent.components[5])
    fmt.println("*** Never Reaches Here ***")
}
```
I've made it look obvious here. However I ran into this error when I didn't correctly handle the `(e: ^Ent, ok: bool)` part of a proc, and used `e` accidentally. So it was tough to track down especially with no line or stack trace since it was a certain proc in the code base that was used.

**Comment by flysand7** [comment]
`Ent` is a pointer to a struct, which you assign a `nil` value to. You dereference a `nil` pointer and that's the cause of crash, I see.

Now the issue is that the crash is happening silently. This is not an Odin issue, but rather the issue with how your shell prints (or actually *doesn't* print) the information that your program has crashed unexpectedly. Can I ask you which shell/terminal you're using?

**Comment by keenfoong** [comment]
Yes, however it does the same thing if I don't explicitly assign a nil to it:
```odin
ent: ^Ent
// or
get_ent :: proc() -> (e: ^Ent, ok: bool) {
   return
}
```
I'm using windows command prompt in VS code. I tested with normal command prompt and powershell also gives nothing.
I used Git Bash (Windows) and it gives a "Segmentation Fault".

**Comment by flysand7** [comment]
If you don't assign it explicitly it's going to get zero-initialized. In the case of pointers that means `nil`. So that's kind of expected.

Regarding the shell not printing anything, it's a quirk of windows. Some developers on windows had told me the way they know when its crashing is that the program shell "hangs" for a while before returning the control back to you. There's not much Odin can do about this.

Setting up a custom event handler for crashing is probably one way to go though

**Comment by keenfoong** [comment]
Odin wont be able to catch the nil dereference? I think a fair amount of languages can detect if invalid memory is trying to be accessed... especially in debug mode.

**Comment by flysand7** [comment]
Depends on what you mean there. It's fairly trivial to set up a default SEH handler on windows / signal handler on unix platforms and print the information that something has gone wrong somewhere. It's a different talk if we are talking about getting the source code location / backtrace, which involves reading the debug info of the executable and reading the stack frames, which is not a trivial amount of work to make this work well.

I'll leave that as an aside, but if you suspect that your program is crashing I suggest you run it via a debugger.

One other thing you could do is to check the `%ERRORLEVEL%` variable after the program has finished executing.

```
$ myprogram.exe
$ echo %ERRORLEVEL%
```

If it prints `-1073741818` (`0xc0000005` converted to signed 32-bit integer, I don't remember whether windows prints them signed or unsigned), then it's an access violation, an invalid pointer dereference.

Returning back to Odin printing the info about the crash though, I don't think it's worth adding the default printing for crashing right now. If it's added I would at least want to get a backtrace but we don't have the right stuff in `core:` library right now to just go ahead and write stack unwinding. There are some plans for `core:debug` which is gonna be useful for that later, in case we decide unwinding on error is worth implementing.

**Comment by jakubtomsu** [comment]
You can also try to use address sanitizer (`-sanitize:address`) if you encounter bugs like this. But this is not valid code, and equivalent C code would cause the exact same crash.
