### ISSUE TITLE
Dynamically setting width format no longer working

### ISSUE THREAD

**Issue by matias-eduardo** [odin-lang/Odin#3605]
After #3566, dynamically setting width in the following way stopped working:

```odin
fmt.printf(
    "[% -[1]*v][% -[3]*v][% -[5]*v][% -[7]*v][% -[9]*v]\n",
    6, "First",
    30, "Second",
    10, "Third",
    20, "Fourth",
    20, "Fifth",
)

// Expected output:
// [First ][Second                        ][Third     ][Fourth              ][Fifth               ]

// Current output:
// [%!*(string=First)v][%!*(string=Second)v][%!*(string=Third)v][%!*(string=Fourth)v][%!*(string=Fifth)v]

```

**Comment by Feoramund** [comment]
Despite it being given in the old examples, that style of format was never supposed to work. The mechanisms in `fmt` have since been updated to reflect the documentation in accordance with how C's `printf` works with regards to argument-specified width.

The correct way to specify width by argument is `%*[1]v`. For example: `fmt.printf("%*[1]s", "Hellope", 16)`
