### ISSUE TITLE
Proposal: tensors

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#364]
This proposal extends the Odin programming language to include [tensors](https://wikipedia.org/wiki/Tensor), a geometric object that maps in a multi-linear manner vectors, scalar, and other tensors to a resulting tensors. They would be very useful in many areas that require linear algebra, such as physics, engineering, and mathematics.

A common form of tensors are rank-2 tensors, also known as matrices.

Concretely, this proposal changes the language as follows:

* Generalizing array programming to higher ranks
* Extends unary and binary `+` and `-` operators and the binary `*` operator to apply to tensors
* Defines a new type that requires the keyword `tensor`
* New built-in procedures for basic tensors: `kronecker_delta`, `levi_civita`, `christoffel`, `weyl`.

Also, it implies corresponding support and extension to support library packages.

Example syntax:
```
Tensor22 :: tensor[rank=2, 2, 2]f32;

a := Tensor22{{2, -3}, { 1, 4}};
b := Tensor22{{4,  3}, {-2, 1}};
c := a * b - a;
fmt.println(c); // {{9.0, 3.0}, {-4.0, 6.0}}

x0 := c[0, 0]; // 9
x1 := c[0, 1]; // 3
x2 := c[1, 0]; // -4
x3 := c[1, 1]; // 6
```

---

This is a partial proposal, conforming to [The Proposal Process](https://github.com/odin-lang/Odin/blob/master/PROPOSAL-PROCESS.md) step 2.

**Comment by bpunsky** [comment]
Hell yes. A couple questions though:

1. It seems these would be compile-time types, analogous to multi-dimensional arrays. How would this relate to slices, then? Would there be a runtime equivalent?

2. Why is it necessary to specify the rank explicitly, when it could be inferred from the number of dimension arguments provided?

3. Is there a specific reason to use the `tensor` keyword rather than just extending arrays to multiple dimensions when there is more than one comma-delineated dimension argument?

This is an excellent proposal, and I'm pretty excited given that I'm too shit at math to implement a tensor library myself.

**Comment by ThisDrunkDane** [comment]
Do we need to have `kronecker_delta, levi_civita, christoffel, weyl` as built-in procedures, or couldn't we have them in a `core:tensor` library? The less built-ins the better afterall.

**Comment by bpunsky** [comment]
@ThisDrunkDane I think the idea is that the tensors would be implemented as array equivalents - i.e. compile-time sized - therefore you would want these procedures to work at compile-time. If there is a runtime equivalent as per my first question, something like a "tensor slice", then I would expect those functions to also be implemented in the `core:tensor` library.

**Comment by gingerBill** [comment]
April Fool's Day has now ended. This proposal was a joke.

**Comment by bpunsky** [comment]
Noooooo
