### ISSUE TITLE
Release download has inconsistent file structure

### ISSUE THREAD

**Issue by JoelNiemela** [odin-lang/Odin#3994]
The latest version (dev-2024-07) has the following file structure:
```
odin-ubuntu-amd64-dev-2024-07.zip
| - dist.zip
    | - dist
        | LICENSE
        | base
        | core
        | examples
        | libLLVM-17.so.1
        | odin
        | shared
        | vendor
```

The previous version (dev-2024-06) had the following file structure:
```
odin-ubuntu-amd64-dev-2024-06.zip
| - dist
    | LICENSE
    | base
    | core
    | examples
    | libLLVM-17.so.1
    | odin
    | shared
    | vendor
```

And the old version dev-2023-12 had the following file structure:
```
odin-ubuntu-amd64-dev-2023-12
| LICENSE
| base
| core
| examples
| libLLVM-17.so.1
| odin
| shared
| vendor
```

This changing directory structure makes updating a scripted install more difficult than it could be — instead of just having to swap "dev-2023-12" for "dev-2024-07", I currently have to do that, as well as unzip the new `dist.zip`, and then move the files inside `dist` to my desired installation location.

Additionally, I see no reason for `dist.zip` and `dist` to exist — they seem like mistakes to me.

**Comment by laytan** [comment]
Yes it has been inconsistent, sorry about that.

The first time it changed we made sure to zip up the files ourselves so that the compiler kept executable permissions after being extracted, it used to only be zipped once by GitHub but they have a long standing issue of not retaining permissions on the files in them.

This did add the annoyance of some nesting, it could probably be made better but it is a complicated system to test and whenever we make changes we (rightfully) get complaints like this that it changed.

If someone wants to figure out a way that makes it 1 zip, with all the files just there, retaining executable permissions on the compiler, it would be ideal, not sure if it is possible though.

**Comment by denovodavid** [comment]
This also breaks package manifests for things like scoop and brew. I think it's fine to have a subfolder if it avoids further issues, it just needs to be consistent so manifests don't need manual updating every release.

**Comment by laytan** [comment]
`brew` and most package managers build their own release/package/manifest from source. Not sure about `scoop`.
But indeed, we should try to avoid changing it much.

**Comment by denovodavid** [comment]
You're right, `brew` is fine. It's `scoop` that mainly relies on prebuilt binaries. They can have an `"extract_dir"` property in their json manifest to unpack a subfolder, but yeah that has been breaking for [odin.json](https://github.com/ScoopInstaller/Versions/blob/master/bucket/odin.json) the past few releases.

**Comment by laytan** [comment]
There isn't anything actionable left here so I will close this.
