### ISSUE TITLE
[Odin test] print statements are shuffled around or disappear

### ISSUE THREAD

**Issue by MrStevns** [odin-lang/Odin#4014]
## Context

While I was trying out the new odin test overhaul, I noticed that the print output from my tests more often than not would disappear or appear on different lines in the terminal output.

I've been able to reproduce the behavior with a test like this:
```
@test
test_printing :: proc(t: ^testing.T)
{
    fmt.println("Hello")
    fmt.println("My")
    fmt.println("World")
}
```

I'm seeing different outputs in my terminal. Sometimes it prints one of the three, other times it's just blank space.
If I only print either "Hello", "My" or "World", then it doesn't appear in the terminal at all.

Output 1:
```
tests  [|                       ]    0/   1 :: test_my_test
1 thread                             0/   1 :: total
Hello
[INFO ] --- [2024-08-03 13:27:35] Starting test runner with 1 thread. Set with -define:ODIN_TEST_THREADS=n.
[INFO ] --- [2024-08-03 13:27:35] The random seed sent to every test is: 78246283136383. Set with -define:ODIN_TEST_RANDOM_SEED=n.
[INFO ] --- [2024-08-03 13:27:35] Memory tracking is enabled. Tests will log their memory usage if there's an issue.
[INFO ] --- [2024-08-03 13:27:35] < Final Mem/ Total Mem> <  Peak Mem> (#Free/Alloc) :: [package.test_name]
tests  [|                       ]         1 :: [package done]

Finished 1 test in 114µs. The test was successful.
```

Output 2:
```
tests  [|                       ]    0/   1 :: test_my_test


[INFO ] --- [2024-08-03 13:29:09] Starting test runner with 1 thread. Set with -define:ODIN_TEST_THREADS=n.
[INFO ] --- [2024-08-03 13:29:09] The random seed sent to every test is: 78537493522690. Set with -define:ODIN_TEST_RANDOM_SEED=n.
[INFO ] --- [2024-08-03 13:29:09] Memory tracking is enabled. Tests will log their memory usage if there's an issue.
[INFO ] --- [2024-08-03 13:29:09] < Final Mem/ Total Mem> <  Peak Mem> (#Free/Alloc) :: [package.test_name]
tests  [|                       ]         1 :: [package done]

Finished 1 test in 122µs. The test was successful.
```

Output 3:
```



[INFO ] --- [2024-08-03 13:29:36] Starting test runner with 1 thread. Set with -define:ODIN_TEST_THREADS=n.
[INFO ] --- [2024-08-03 13:29:36] The random seed sent to every test is: 78622784691056. Set with -define:ODIN_TEST_RANDOM_SEED=n.
[INFO ] --- [2024-08-03 13:29:36] Memory tracking is enabled. Tests will log their memory usage if there's an issue.
[INFO ] --- [2024-08-03 13:29:36] < Final Mem/ Total Mem> <  Peak Mem> (#Free/Alloc) :: [package.test_name]
tests  [|                       ]         1 :: [package done]

Finished 1 test in 117µs. The test was successful.
```

As you can see, "Hello" only appear in one of the three outputs, while the other two shows just blank space. 
It's also worth noting that the "tests  [|                       ]    0/   1 :: test_my_test" also disappear in `Output 3`

# Odin Report
```
Odin:    dev-2024-08:ac483f72e
OS:      macOS Monterey 12.7.2 (build: 21G1974, kernel: 21.6.0)
CPU:     Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
RAM:     16384 MiB
Backend: LLVM 18.1.8
```

# Other details:
- macOS Terminal: zsh

## Expected Behavior
I expect to see all three prints in the terminal:

Hello
My
World

## Current Behavior
The current behavior is that it sometimes prints "Hello" while other times there's no printed output except blank space.
I haven't been able to get the entire input as of yet. Most of the time, the statements are eaten by the test output.

### Steps to Reproduce
- Write a small test program with the example given above
- Run it using `odin test`
- Check output in terminal

**Comment by MrStevns** [comment]
Damn it... didn't mean to publish it... filling it out asap.

**Comment by Kelimion** [comment]
I've let @Feoramund know.

**Comment by laytan** [comment]
Can confirm, I think this is because the nice graphics take over the terminal output, I've found for reliable output you should use `core:log`

**Comment by Kelimion** [comment]
That's my inclination as well. That's why I didn't apply the `bug` label, as it may well be a side effect of intended behavior.

**Comment by laytan** [comment]
Thinking about this a bit, when os2 is done, the test runner could set os2.stdout, os2.stderr to a custom implementation that does the synchronisation that is now done with logs. That doesn't help the current situation though because os.stdout and os.stderr are file handles and not an abstract File as in os2.

**Comment by MrStevns** [comment]
I have no problem using log instead, especially if that's the intended way.

**Comment by Kelimion** [comment]
Especially if you have several tests. They're being run in parallel, and it would be all too easy for several print statements to get interleaved. Even part of a print statement might be interrupted by other threads.

**Comment by Feoramund** [comment]
Right, so this isn't so much _intended behavior_ as it is something that is unable to be worked around right now. If you want to print something, you're strongly encouraged to use `core:log`, as we moved all test printing to that instead for the reasons that Kelimion has listed.

> Thinking about this a bit, when os2 is done, the test runner could set os2.stdout, os2.stderr to a custom implementation that does the synchronisation that is now done with logs. That doesn't help the current situation though because os.stdout and os.stderr are file handles and not an abstract File as in os2.

This would be nice if it ends up being possible. Though, I'd still encourage the use of `log` so you can select different levels (warn, debug, et cetera) and use the actual underlying interface. What would be really helpful is if we could get the non-panic/assert runtime printing (bounds-checking errors, possibly another I've forgotten) into the logging interface somehow, though that might be a bit too low level to tinker with.

Another consideration is that if `stderr` ends up being redirected to `log`, a decision will have to be made whether or not that counts as an error for the test to have failed or not. I'd say if this ends up being how `fmt` works in the future with `os2` it should be only as a fallback for new programmers or to catch output from called procedures which are test-unaware.

I didn't make it explicit that you're not supposed to use `fmt` in [the documentation](https://odin-lang.org/docs/testing/#logging) I wrote for `core:testing`, but at least there's an example there of using `core:log`. In closing, I will say that this is not a bug, as test writers are expected to use the `core:log` interface instead, and perhaps in the future we might be able to have a fallback, but it would only be a fallback and not the preferred manner of printing during tests.

As a side note, due to the multi-threaded nature of the runner's execution, if you need several contiguous lines to be printed all at once to look nice (benchmark output, perhaps), you're encouraged to build the string first, then print it in one go, instead of relying on execution order.

**Comment by MrStevns** [comment]
> I will say that this is not a bug, as test writers are expected to use the core:log interface instead, and perhaps in the future we might be able to have a fallback, but it would only be a fallback and not the preferred manner of printing during tests.

While I did read that you should use `log` for printing, from the PR itself, I just didn't expect that it meant that my fmt prints would get borked but given the way it structures the output, it makes sense now.

Still, if fmt print messes up the output and that's expected for now, would it be possible to ignore them when using `odin test`? The confusion for me comes from the fact that it sometimes prints things out. had there been no print output at all, then I might have asked `How do I print to console after the test overhaul` on Discord or delved into the documentation rather than make an issue here.

**Comment by Kelimion** [comment]
> Still, if fmt print messes up the output and that's expected for now, would it be possible to ignore them when using `odin test`?

No, because `core:log` relies on `core:fmt`, so we can't just tell `core:fmt` to do nothing when `ODIN_TEST` is defined. The test would have no output at all. It would need a very involved bit of plumbing to do this in a way that doesn't disadvantage `core:fmt` under normal circumstances.

> The confusion for me comes from the fact that it sometimes prints things out. had there been no print output at all, then I might have asked `How do I print to console after the test overhaul` on Discord or delved into the documentation rather than make an issue here.

That's because of the test runner's fancy output using ANSI control codes to move the cursor around. `fmt` very likely actually does print, it just gets overwritten at some point. You could redirect the output to a file to verify whether that's the case and the printed strings appear there.

**Comment by MrStevns** [comment]
I thought as much but I wanted to ask to be safe.
Let's close the issue with that comment.

Thank you for clarifying

**Comment by Kelimion** [comment]
Laytan did raise a good point that once the `core:os` rewrite is ready, stdout and stderr will be streams we can easily intercept / give a different implementation, so that even if you then used `fmt.printf` within a test, the test runner's wrapper around it could take care to synchronize the output.

But for now, `core:log` is indicated. Thanks for the question.
