### ISSUE TITLE
Fail compiling odin from git source

### ISSUE THREAD

**Issue by hirochirac** [odin-lang/Odin#4018]
* Windows 11 odin version : dev-2024-08

When i try to compile odin, I obtain the error message as follow:
libucrt.lib(checkcfg.obj) : error LNK2001: symbole externe non résolu _guard_check_icall_$fo$
I:\lang\odin\demo.exe : fatal error LNK1120: 1 externes non résolus

**Comment by Kelimion** [comment]
That's not a lot to go on.

Where we ask for `odin report` in the bug template, it's because it also includes things like which LLVM version, the Windows build version, etc.

But the error here suggests that `odin` didn't actually fail to compile, it's `examples\demo` built by Odin *after* compiling the compiler that's failing to link here.

When you run `odin` from within `i:\lang\odin` does it do anything or does the command prompt say "command not found"?

What version of Visual Studio / Windows platform SDK is installed?

**Comment by laytan** [comment]
Gonna close this because we haven't gotten a response.
