### ISSUE TITLE
add compiler switch to disable the silent implicit dynamic allocation from m[k] = v to a zero length map

### ISSUE THREAD

**Issue by yohn-kohl** [odin-lang/Odin#4109]
Add compiler switch to disable the silent implicit dynamic allocation from `m[k] = v` to a zero length map one that is declared but has no pairs and has zero length

Line 2 in the code below dynamically allocates memory using the assignment operator
```cpp
main :: proc() {
  my_map_1: map[string]int // line 1 - no allocations
  my_map_1["Month"] = 8    // line 2 - dynamically allocates
}
```
This is not shown or said in the documents

There is no procedure in the documents for this or showing this it is in the `base/runtime/dynamic_map_internal.odin` source code which you must know about

This unknown switch not in the odin help build `-no-dynamic-literals` does not disable `m[k] = v` to a zero length map and stop or error or warn against the implicit allocation, it only stops this `x := map[string]int{ "hi" = 0 }` even if the map is zero or already allocated
this switch is not applicable to the request since the request is not a literal - so the existing switch does not make sense to disable the `m[k] = v`  silent allocation.  

Recommend a switch is added to the compiler to disable this on the programmer's choice and the switch should also stop the implicit dynamic allocation someone said also happens for a dynamic array in a similar situation and any other silent implicit dynamic allocations

**Comment by gingerBill** [comment]
* 1. https://github.com/odin-lang/odin-lang.org
* 2. We don't include anything private, especially things with `_` prefixes. So adding them there is still not a good idea. 
* 3. That's what I meant with "The better solution is to just document it."
* 4. is wrong. There is still no operator overloading. Please don't confuse people this is as it i is literally not OPERATOR OVERLOADING. This is just how the "operator" is defined for that **built in** type. That's like saying `+` is overloaded because it works for multiple types. No one uses the term that way.

**Comment by gingerBill** [comment]
> but you are a good person to document this and I will submit to link you provided

And please don't use this manipulative language.
That's arsehole behaviour.

**Comment by gingerBill** [comment]
From what was said on the Discord. You did say that English is not your native language, and I apologize for that. However, that phrase in English is not polite and very manipulative; it implies that to be a "good person" I should do what _you_ say.
