### ISSUE TITLE
Make slice out of underlying using array

### ISSUE THREAD

**Issue by ghost** [odin-lang/Odin#42]
Currently for a variable `v` of type:
```C
vec3 :: raw_union {
  using array: [3]f32,
  using elems: struct { x, y, z: f32 }
}
```
you can access its elements with `v[0]`, `v[1]`, `v[2]` just fine, but making a slice as `v[..]` currently won't work, throwing:
```
Cannot slice `v`
```
error. Explicitly getting `v.array[..]` works, but it would be nice if slicing could respect `using` keyword :)

**Comment by gingerBill** [comment]
I'm not sure if I want to support `using` still on arrays. I added to as an experiment to see what it would be like and for especially the purpose you've made.

It may be needed to take `using` to its logical extreme but I really don't know if that would _feel_ right.

**Comment by procedural** [comment]
@gingerBill well, the experiment is surely working, for me at least ;) Except this case...

**Comment by procedural** [comment]
Ok, doing vec3 this way is currently limited in 3 ways for me:
1. `raw_union`s are not printable
2. You can't init such type with `vec3{}` constructor
3. Actually, due to the way `find_using_index_expr` works, currently you can remove `using` tag from the `array` variable and it'll still work :)

So yeah, I'd be fine with `to_slice :: proc(any_of_my_structs: any) -> []f32` function that'd return `[0..<3]` slice, but don't know how to implement it yet :P

**Comment by gingerBill** [comment]
Issue 3 has been fixed.
Issue 2 is a problem because, which variant will you print?
Issue 1 is because of weird reasons. I may change this soon to be similar to C.

**Comment by procedural** [comment]
@gingerBill printing is not crucial given I can always print it by accessing elements manually :) But the `vec3{}` constructor is a problem, I switched to regular structs because my code started to look ugly...

**Comment by gingerBill** [comment]
@procedural Is there any reason for not using `[vector 3]f32`? Is it just its alignment that is the issue?

**Comment by procedural** [comment]
I get 2 errors when replacing `vec4 :: struct { x, y, z, w: f32 }` with `vec3 :: [vector 4]f32;`:

For a versor initialization like `v := vec4{w = 1};`:
```
`field = value` is only allowed in struct literals
```
For accessing `x`, `y`, `z`, `w` without typing the name of a variable each time in a scope:
```
`using` can only be applied to variables of type struct or raw_union
```

**Comment by procedural** [comment]
I'd love to use `[vector n]f32` if at least I could apply `using` to them :)

**Comment by gingerBill** [comment]
This is because `[vector 4]f32` is not a struct, it's a vector. Vectors are like arrays that have certain rules and operations. 

The members `x` `y` `z` `w` are short hand for vectors of length 4 and less. They could be removed because it's just a "sanity" feature.

```
a := [vector 4]f32{1, 2, 3, 4};
b := [vector 4]f32{1}; // equivalent to `[vector 4]f32{1, 1, 1, 1};
```

At the moment, it is not possible to initialise an array with element at certain indices yet. I may add this soon.

**Comment by procedural** [comment]
What's about `using` a vector?
