### ISSUE TITLE
(BUG) Compiler crash (.cpp assertion) due to non-exact integer value from casting

### ISSUE THREAD

**Issue by galt-john** [odin-lang/Odin#4225]
### Hardware and Software
2024-09 Odin Master Repo (release build)
Windows 11 Intel x64 CPU
Fails on build and/or run
### Symptoms
Compiler crash, best seen by running code below
```odin
package main
import "core:fmt"
main :: proc() {
	_ := transmute(i64)(u64(0.1))
}
```
### Error
\odin\src\check_expr.cpp(3618): Assertion Failure: `src_v.kind == ExactValue_Integer`
Cpp Source Code link and specific code line in error:
Line 3618 of .cpp source (https://github.com/odin-lang/Odin/blob/d783bca2979db5955885ee6b2a06f20f8a847582/src/check_expr.cpp#L3618) 
### Expected Behavior
No compiler crash and appropriate compiler warning/error

**Comment by Kelimion** [comment]
The problem arises because `o->value` here is a float:
```cpp
ExactValue src_v = exact_value_to_integer(o->value);
GB_ASSERT(src_v.kind == ExactValue_Integer);
```
And when `exact_value_to_integer(o->value)` is evaluated, this procedure casts it to an `i64` and back to an `f64`. If the `f64` is not equal to the original `ExactValue_Float`, then instead of returning `exact_value_i64`, it falls through the rest of `value_to_integer` to the part where it returns "Invalid".
```cpp
case ExactValue_Float: {
	i64 i = cast(i64)v.value_float;
	f64 f = cast(f64)i;
	if (f == v.value_float) {
		return exact_value_i64(i);
	}
	break;
```
This probably means that this should've either been caught earlier in the `u64(0.1)` process, or we need to allow `exact_value_to_integer` to truncate. I don't know what the ramifications of the latter would be without checking where and how else it's used.
