### ISSUE TITLE
adding 0, then -0 to map[f32]struct{} creates two different entries

### ISSUE THREAD

**Issue by bingis-khan** [odin-lang/Odin#4309]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Odin:    dev-2024-09:16c5c69a4
OS:      macOS Catalina 10.15.7 (build: 19H15, kernel: 19.6.0)
CPU:     Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
RAM:     4096 MiB
Backend: LLVM 18.1.8

## Current Behavior

This code (excluding import and package declaration):

```odin
main :: proc() {
	w: f32 = 0.
	v: f32 = -0.

	m := make(map[f32]struct{})

	m[w] = {}
	m[v] = {}
	
	fmt.println(m)
}
```

creates two different entries for 0 and -0.

println prints: `map[0={}, -0={}]`

## Expected Behavior

One entry should be created.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. add package and import declaration
2. run the code
3. ???
4. profit

### Failure Logs
n/a

**Comment by laytan** [comment]
This is expected, have a look into the IEEE floating point standard to see these are indeed 2 distinct values.

**Comment by bingis-khan** [comment]
@laytan but in Odin, 0 == -0. shouldn't the behavior be equivalent?

**Comment by flysand7** [comment]
If we're talking about integers, that would be the case, but you have declared the map as:

```odin
m := make(map[f32]struct{})
```

Which is a map, where `f32` is used as a key. When you use the values `0` and `-0`, the way type inference works is that it will deduce the type of these values as `f32` and interpret them as such, so these literals stand for `+0.0` and `-0.0`.

Odin for the most part follows IEEE754 specification for implementing floating-point numbers. In that specification, `+0.0` and `-0.0` are defined as separate entities, which are encoded slightly differently (all bits zero except for the sign bit).

This behavior can seem off-putting because typically `-0` represents an integer, and for integers `-0 == 0`, but in this case the types of literals aren't integers. I hope this clears up some of the confusion and explains why this is the expected behavior.

**Comment by bingis-khan** [comment]
@flysand7 I know about the different encoding, but what they are defined to be equivalent. The actual code I was referring to is:

```odin
	w: f32 = 0.
	v: f32 = -0.
	fmt.println(w == v)

```

which prints `true`.

**Comment by flysand7** [comment]
@laytan can we get a clarification on how the map keys are meant to be compared against each other, or at least re-open this issue? I feel like some things weren't properly communicated

**Comment by laytan** [comment]
A map hashes bitwise and doesn't use equality at that point, after hashing and finding a match equality is checked.

**Comment by flysand7** [comment]
Guess that answers it

**Comment by bingis-khan** [comment]
Speaking of that, I wonder if there is a standard way to "normalize" floats like that, where each -0 is turned into 0 (including the IEEE-754, but I believe this happens automatically)?

**Comment by laytan** [comment]
Hmm let me reopen this for Bill to look at actually, looks like at least Go normalizes the float like you suggested should happen.

**Comment by gingerBill** [comment]
I am not normalizing the floats. `-0` isn't `+0`. Go might normalize this but I do not want to do this.

I understand the logic that `+0 == -0` is true therefore the hashes should be the same, however relying on a float as a key is itself a kind of dodgy thing. This leads down the path of oddities when it comes to NaN too.
