### ISSUE TITLE
build.bat fails on newest Windows 11 versions because wmic was removed from the latest versions.

### ISSUE THREAD

**Issue by MrMetube** [odin-lang/Odin#4345]
## Context

I reinstalled my windows 11 and found that the build.bat fails with an error message like 
```
ERROR command "wmic" not found ...
```

## Steps to Reproduce

1. Get a clean install of windows 11 (maybe updating to the newest version also suffices)
2. Follow the official install guide on the [odin website](https://odin-lang.org/docs/install/)
3. Once you try to build the compiler with build.bat you get the error

## Suggestion

The wmic command is only used to get the date(i.e. year month day) as a variable. Please use any other command that does the same,

**Comment by flysand7** [comment]
Some info:

This can be a little bit problematic to do uniformly across all platforms the `date` command prints the date using regional format, which can't be then reliably parsed (see below)

![image](https://github.com/user-attachments/assets/5eab50ab-7088-42dc-af39-d8e3267ace53)

From what I see it should be possible to use the Windows Powershell (`powershell.exe`) to get the current date.

![image](https://github.com/user-attachments/assets/5545446f-00cc-4a42-b535-1d545eb28e7d)

I'm not sure if we're supporting Windows 7, but if we do, the suggested course of action is:

1. Check if wmic is present. If it is, do the old thing.
2. Otherwise use Windows Powershell to get the date.

Of course this could also be done by checking for powershell first.

**Comment by laytan** [comment]
Fixed in #4352
