### ISSUE TITLE
fmt.print does not print correctly on Windows

### ISSUE THREAD

**Issue by quarkstuff** [odin-lang/Odin#4386]
## Context

The `fmt.print` procedure is printing the wrong text for unicode characters on windows

* OS: Windows 11, 23H2
* Odin Version: dev-2024-10:af9ae4897

## Expected Behavior

Console output: `µ`

## Current Behavior

Console output: `┬╡`

### Steps to Reproduce

Run the following code:
```odin
package main

import "core:fmt"

main:: proc() {
	fmt.print("µ")
}
```

**Comment by Lperlind** [comment]
This is probably because your terminal is set for utf16 (the default) not utf8.
You can enable system wide utf8 by going to:

settings > language > administrative language settings > change system locale

Then check "Beta: Use Unicode UTF-8 for worldwide language support"
![image](https://github.com/user-attachments/assets/b16d1649-0593-4e9a-a241-6c147010cb36)

**Comment by blob1807** [comment]
You need to tell the window console to use the UTF-8 code page. By default it'll be 437 or 1252, which are extended ASCII.
import `core:sys/windows` and add `windows.SetConsoleOutputCP(.CP_UTF8)` to the start of main. Note this sets the console's code page until further notice.

**Comment by Kelimion** [comment]
`fmt` prints what it's told to print. As the others have observed, this is a problem caused by a Windows terminal set to the wrong codepage.

We could set `SetConsoleOutputCP` at the start of the program for you before `main` is entered, but then you lose the flexibility to call [GetConsoleOutputCP](https://learn.microsoft.com/en-us/windows/console/getconsoleoutputcp), save the original codepage, and restore it as the program exits should you have a reason to do that.

**Comment by Lperlind** [comment]
> `fmt` prints what it's told to print. As the others have observed, this is a problem caused by a Windows terminal set to the wrong codepage.
> 
> We could set `SetConsoleOutputCP` at the start of the program for you before `main` is entered, but then you lose the flexibility to call [GetConsoleOutputCP](https://learn.microsoft.com/en-us/windows/console/getconsoleoutputcp), save the original codepage, and restore it as the program exits should you have a reason to do that.

couldn't we just do that though?

**Comment by Kelimion** [comment]
> couldn't we just do that though?

That's something you might want to do if you build a full screen (TUI) terminal app. But if have a CLI app that outputs UTF-8 and you switch back the codepage at program exit, then what you just printed might turn right back into garbage again *, defeating the purpose of switching the codepage.

At the end of the day this is a Microsoft problem, who should've adopted UTF-8 throughout the codebase in Win2k. The same problem also exists on Linux terminals in theory. We just never see it because distros set the locale to a UTF-8 one by default.

But I also think it's up to the programmer to decide whether it's acceptable for them to change the codepage at the program's start, and not something we should enforce in the program entry point, precluding you from grabbing the original codepage - which would now return UTF-8 if queried - in case you want to restore it.

* Depending on whether the terminal implementation uses the same codepage for the entire buffer, or performs the translation text comes in.
