### ISSUE TITLE
odin test console logger and fmt.printf not finishing flushing

### ISSUE THREAD

**Issue by gco-bmx** [odin-lang/Odin#4396]
## Context

running below via `odin test` does not output the complete string on the console.
I see the same behavior with the console logger, 
when step debugging after `io.flush(w)` in `wprintf` in `fmt.odin`, I see the full string
using `odin run` full string is output running equivalent from main 
same behavior in command prompt and powershell

```odin
@(test)
parser_basic :: proc(t: ^testing.T) {
  b := strings.builder_make()
  fmt.sbprintf(&b, "i:%v", 0)
  for i:=1; i < 4096*16; i+=1 {
    fmt.sbprintf(&b, ",i:%v", i)
  }
  fmt.printf("str:%v\n", transmute(string)b.buf[:])
  testing.expect(t, strings.builder_len(b)!=0, "there was an error")
}
```

`odin test tests/ -all-packages --collection:src=src -debug`

* Operating System & Odin Version: Window 10, Odin 9f609dd

## Expected Behavior

console output ends with
`,i:65532,i:65533,i:65534,i:65535`

## Current Behavior

console output ends with
`i:65505,i:65506,i:`

**Comment by Feoramund** [comment]
Tests are meant to use the `core:log` logging API, not any of the direct `core:fmt` printing procedures. This is because the test runner is multi-threaded, and the logger is setup to handle interleaving and flushing those messages correctly. `fmt.println` and friends all go straight to `stdout`, whereas the loggers setup for each test runner thread send the messages to the main thread for later organizing and printing.
