### ISSUE TITLE
mutex_unlock on unlocked mutex unreachable()

### ISSUE THREAD

**Issue by fallenleavesgocrunch** [odin-lang/Odin#4496]
sync mutex_unlock states that if the mutex is unlocked it is a no-op to unlock it. When doing this from a single thread there is no issue; but when doing it from a second thread it reaches an unreachable() call in on macOS:

```
atomic_mutex_unlock
    ...
    switch atomic_exchange_explicit(&m.state, .Unlocked, .Release) {
    case .Unlocked:
        unreachable()
```

Either the unreachable shouldn't be there or the docs are wrong.

Simple test program to reproduce the problem:

```
package main

import cs "core:sync"
import ct "core:thread"

test_unlock :: proc(thread: ^ct.Thread) {
    lock := cast(^cs.Mutex)(thread.data)

    // a double unlock. The second unlock according to the docs should be fine but hits an unreachable()
    cs.mutex_unlock(lock)
    cs.mutex_unlock(lock)
}

main :: proc() {
    lock: cs.Mutex

    // initial lock
    cs.mutex_lock(&lock)

    // set up the test thread
    thread := ct.create(test_unlock)
    defer ct.destroy(thread)
    thread.data = &lock
    ct.start(thread)

    // lock again to block until test thread unlocks
    cs.mutex_lock(&lock)

    ct.join(thread)
}
```

**Comment by laytan** [comment]
Proper resolution would be to see what the behavior is on windows (which we don't control because it's just a win32 api) and reflect that onto this behavior, so it's consistent.

**Comment by Feoramund** [comment]
We implement mutexes natively in Odin with atomics for non-Windows platforms, so this will happen for others as well. Windows is the only platform that uses a system-specific API for them (futexes are a different case.) Unfortunately, [the documentation](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-releasesrwlockshared) has no statement on what happens when you unlock an unlocked Slim Read/Writer lock.

Are SRW locks preferable to native atomics? Is it that they are faster than the `_futex_wait` implementation for Windows?

**Comment by laytan** [comment]
Yep, SRWLock is much faster which is why we use it instead. Microsoft has done a bunch of optimizations with some even relying on internal logic in the kernel (afaik).

**Comment by laytan** [comment]
Actually the minimal reproduction case is:
```odin
package write

import "core:sync"

main :: proc() {
	mu: sync.Mutex
	sync.mutex_unlock(&mu)
}
```

Windows is fine with it, so I've now made the other targets also be.
