### ISSUE TITLE
-sanitize:address gives Undefined symbol error

### ISSUE THREAD

**Issue by clankill3r** [odin-lang/Odin#4630]
## Context

The `-sanitize:address` option gives:

> Undefined symbols for architecture arm64:
  "___asan_version_mismatch_check_v8", referenced from:
      _asan.module_ctor in main.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

* Operating System & Odin Version:

> Odin:    dev-2024-12:597fba7c3
> OS:      macOS Sequoia 15.1.1 (build 24B91, kernel 24.1.0)
> CPU:     Apple M3
> RAM:     24576 MiB

## Expected Behavior

Either that it works, or a message that it is not supported on the specific platform

## Current Behavior

See error above

### Steps to Reproduce

Use `-sanitize:address` on OSX with apple silicon.

**Comment by spahnke** [comment]
Odin ships with LLVM 18 which does not support ASAN on Apple Silicon. LLVM 19 does though. If you have LLVM 19 installed via Homebrew you can do e.g.

```sh
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
odin build . -sanitize:address
```

in your build script.

**Comment by laytan** [comment]
Almost, right solution but wrong cause.

It does not work with clang that comes with macOS by default, so you have to make brew's llvm be used by Odin, that can either be done with the `ODIN_CLANG_PATH` environment variable or by adding the brew directory to your path. Brew maintainers do advise against adding that to your path because it can interfere with other things, I have never personally had those issues though.

**Comment by spahnke** [comment]
Oh, I guess that is what confused me, thank you 🙇‍♂️ The ASAN is enabled through the linker call which is a system call anyway and has nothing to do with the shipped LLVM lib for code generation.

**Comment by clankill3r** [comment]
I'm confused, but anyway, this works so maybe there is no reason to be confused:

I added:
`export ODIN_CLANG_PATH="/opt/homebrew/opt/llvm/bin/clang-19"`
to my `~/.zprofile` file.
