### ISSUE TITLE
assert and #assert

### ISSUE THREAD

**Issue by PavelVozenilek** [odin-lang/Odin#491]
This is very minor feature request, something nice to have.

`assert` and `#assert` work as expected. However, in some cases the condition in `assert` can be resolved in compile time. Currently the compiler doesn't do it.

This example:

```
package main
import "core:fmt"
main :: proc() {
    assert(false);
}
```
fails only at runtime.

In some cases `#assert` condition may not be direct literal value, but could be resolved as such by analysis.

This example:

```
package main
import "core:fmt"
main :: proc() {
    x : int = 1;
    y : int = 2;
    #assert(x == y);
}

```
fails to compile.

**Comment by gingerBill** [comment]
This is not something I want. I quite commonly write things like `assert(false);` and want it only ever be called at run time. `panic` is usually a better thing for that.

As for the example with `#assert`, that's because `x` and `y` are variables and not constants. Constants are purely compile time values. Even if those variables are known to have particular values at compile time, due to how I want the type system to work, they are not constants.

**Comment by PavelVozenilek** [comment]
I see. Ideally, there could be another form of assert, one which is not expected to fire and not checked at compile time, like:

```
...
if x < 0 {
  unexpected_assert(false);
  return 0;
}
...
```

It may sound as over-engineering, but such a plenty is useful for heavily defensive code. (For example, I have special assert for code paths which handle unlikely bugs. It fires when running normal code, but inside tests which verify these unlike paths, it stays silent. This allows me to be super defensive and still be able to test it.)
