### ISSUE TITLE
Linking bug (wayland-protocols)

### ISSUE THREAD

**Issue by Pestdoktor** [odin-lang/Odin#547]
## Context

* Operating System: GNU/Linux (void glibc x86_64)
* Odin version/Commit: current master (357e7265)

## Failure Information

Trying to link against `wayland-protocols` / `xdg-shell` fails.

### Steps to Reproduce

```
#!/bin/env bash

curl -OJ https://raw.githubusercontent.com/wayland-project/wayland-protocols/master/stable/xdg-shell/xdg-shell.xml

wayland-scanner private-code xdg-shell.xml xdg-shell.c

clang -shared -o xdg-shell.so xdg-shell.c

cat << EOF > foreign-test.odin
package main

foreign import xdg "xdg-shell.so"

wl_interface :: struct {
	foo: int
}

foreign xdg {
	xdg_wm_base_interface: wl_interface;
}

main :: proc() {
	xdg_wm_base_interface = wl_interface{1};
}
EOF

odin run foreign-test.odin
```

### Failure Logs

```
/bin/x86_64-unknown-linux-gnu-ld: foreign-test.o: in function `main.main':
foreign-test.ll:(.text+0x3313): undefined reference to `xdg_wm_base_interface'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by gingerBill** [comment]
Is this still a problem?

**Comment by sci4me** [comment]
I just tried to replicate this and ran into a different error from `opt`:
```
opt: Unknown command line argument '-die'.  Try: 'opt --help'
opt: Did you mean '--dce'?
```
Directly after running `odin run foreign-test.odin`.

OS: 5.11.8-arch1-1
Odin: tag v0.13.0 (I'd be using latest but I'm having an issue due to LLVM being updated to v12 -- apparently Odin isn't liking that for some reason (make fails))

**Comment by gingerBill** [comment]
@sci4me That error message you have with `opt` is literally none existent on the latest versions on Odin because it uses the LLVM C API directly.

Unfortunately there two problems out of my hands:

* Arch has forced everyone to use LLVM 12 and for some reasons you cannot get LLVM 11 anymore for that distro (what the fuck has happened here?!)
* I attempted to upgrade Odin to LLVM 12 last night and it appears that LLVM 12 is fundamentally broken (with the C API) and those problems are not fixed until the next (official) version of LLVM is out (LLVM 12 is a write-off for Odin)

**Comment by PaytonTheMartian** [comment]
I fixed this using `sudo pacman -Rd --nodeps llvm` (Forces removal, ignoring dependency errors) to remove the non-llvm11, then `sudo pacman -S llvm11`

Please note that removing LLVM will probably break some packages, so make sure to confirm what things depend on LLVM before running `-Rd --nodeps`
