### ISSUE TITLE
map iteration syntax question

### ISSUE THREAD

**Issue by DEADB17** [odin-lang/Odin#548]
Not a feature request nor an issue but a question...

Browsing the docs I was surprised by the asymmetry of iterating over a map (last case below)
```odin
for character, index in some_string {
    fmt.println(index, character);
}
for value, index in some_array {
    fmt.println(index, value);
}
for value, index in some_slice {
    fmt.println(index, value);
}
for value, index in some_dynamic_array {
    fmt.println(index, value);
}
for key, value in some_map {
    fmt.println(key, value);
}
```
Given how symmetrical the rest of the syntax is I was expecting the `key` and `value` to be reversed.
```odin
for value, key in some_map {
    fmt.println(key, value);
}
```
Is it intentional? if so, what's the reason?

P.S.: Great work, looks very promising.

**Comment by gingerBill** [comment]
This is intentional but it's also weird. The `map` type is the odd-ball here in general.

Most of the time, you don't need the `index`, so if you omit it, it still looks correct:
```odin
for value in some_array {
}
```

As for maps, you usually want to know the key as well as the value, and rarely the value on its own. This is why it is `for key, value in some_map {}`
