### ISSUE TITLE
Members known across all variant types in a discriminated union should be accessible without knowing the union's specific type.

### ISSUE THREAD

**Issue by John-Minor** [odin-lang/Odin#570]
In the following excerpt each variant type in the `Node` discriminated union has a `Token` member at the top. They all have the same type by the same name at the same memory offset, so it should be possible to access these fields without caring about the specific type of the union.
```
Node :: union
{
    Token,
    Unary_node,
    Binary_node,
}

Token :: struct
{
    character :rune,
    precedence :i8,
    position :u32,
    nullable :bool,
    first_pos :map[u32]u32,
    last_pos :map[u32]u32,
    follow_pos :map[u32]u32,
}

Unary_node :: struct
{
    using operation :Token,
    middle :^Node,
}

Binary_node :: struct
{
    using operation :Token,
    left :^Node,
    right :^Node,
}
```
Currently to get this behavior I have to do something like this:
```
    {
        token :Node = Token{nullable = false};
        token_ptr := cast(^Token)&token;
        fmt.println(token_ptr.nullable);

        bin_node :Node = Binary_node{operation = token_ptr^};
        bin_ptr := cast(^Binary_node)&bin_node;
        fmt.println(bin_ptr.nullable);
    }

    {
        token :Node = Token{nullable = true};
        token_ptr := cast(^Token)&token;
        fmt.println(token_ptr.nullable);

        bin_node :Node = Binary_node{operation = token_ptr^};
        bin_ptr := cast(^Binary_node)&bin_node;
        fmt.println(bin_ptr.nullable);
    }
```
And the issue with doing it via cast is I might slip up and change the layout of my types and not realize that I'm causing a problem elsewhere. If this feature were in the language, then the compiler would alert me as soon as I've made a change to my layout that prevents it from agnostically accessing data.

**Comment by Tetralux** [comment]
The issue perhaps is that the token may be `nil`; it may not have any variant set. If it isn't set and you try to access one of the fields, that seems wrong.
In practice, maybe it's fine because they're required to be there, however.

Being able to do `my_node.character` (one of `Token`'s fields)--or even just `my_node.token` assuming the `Token` field is called `token` everywhere--seems like it would be useful, but probably would not be default behavior.

Maybe you'd annotate the union with a tag - maybe something like:
```odin
Node :: union #require_prefix_field(Token) // compiler checks that all variants in the union have a Token as the first field
{
    Unary_node,
    Binary_node,
}
```

If I'm understanding right, you wouldn't need the `Token` as one of the variants anymore either.

**Comment by gingerBill** [comment]
The issue here is that `union` can be `nil` and thus this parameter may not be valid.
