### ISSUE TITLE
question: Do you have any intent to implement the entire compiler infrastructure in Odin?

### ISSUE THREAD

**Issue by delata** [odin-lang/Odin#664]
Like how Go project did.

Thanks.

**Comment by gingerBill** [comment]
The original plan was when v1.0 of Odin is out, which includes are written specification and the compiler adhering to the specification. The v1.0 compiler will be written in C++. v1.1 will most likely be getting the Odin compiler written in Odin.

However, before v1.0, the core library will be containing a full compiler frontend for Odin written in Odin which can be used for many tools (especially metaprogramming tools). 

This library version of the frontend will most likely be separate from the actual compiler's code because the compiler will be optimized more for performance rather than usability.

**Comment by delata** [comment]
thank you for you nice answer.
