### ISSUE TITLE
Documentation Generation

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#74]
I'm currently writing the documentation generation tool for Odin. So if you pass it a file with valid syntax, it will generate the documentation for the file from just its associated comments.

So a a procedure declaration with a group of comments above it will be associated with that group of comments.
```
// foo_bar does amazing things beyond your wildest dreams
// It does this by doing magic behind your very eyes
proc foo_bar(name: string, loc = #caller_location) -> int {
    return 42;
}
```

What format would be preferable for documentation?
* Markdown
* HTML
* Custom format
* Other?

**Comment by ratchetfreak** [comment]
Is there a way to differentiate doc comments from comments that shouldn't be in docs?

**Comment by bdoner** [comment]
Some languages goes with three slashes for documentation comments and two for regular comments.

Doing it directly in HTML allow for easy online docs. Though Markdown is better for GitHub project, and will easily convert to HTML if that's needed. So Markdown +1 from here!

**Comment by gingerBill** [comment]
@ratchetfreak There will not be. I don't personally like this as one of the points of comments is for documentation. Why should there be a completely different way to handle this specific case?

They way it will work is that it will grab the leading comment before the declaration and the line comment after the semicolon (for specific declarations).

Subsequent lines of text will be considered part of the same paragraph (like markdown) so if you want a line break, leave an empty comment to separate paragraphs.

I want comments in code to be just as documenting as the generated documentation.

**Comment by ThisDrunkDane** [comment]
I say +1 for markdown too though will markdown in the comment be stripped our can you embed markdown in your comments?

**Comment by msmshazan** [comment]
Markdown is more sane than HTML or XML or any *ML ....

**Comment by clankill3r** [comment]
1.
Markdown +1
You have browser extensions to support markdown in the browser.
The one I tested for chrome works (you have to enable for files in options):
https://github.com/simov/markdown-viewer#advanced-options

It might be good to make people aware of that. Prior to this day I always looked at md files in simple text editors that don't support the format.

2. Also please generate links to other files of the documentation.
For example, here you can click on String as well to go to the documentation of String:
http://processing.github.io/processing-javadocs/core/processing/core/PApplet.html

3. Like @bdoner said with 3 slashes, java has /** instead of /* for example. I don't really care what it looks like but I think it would be good to have it more specific then just taking the comments above a proc.
-some IDE's highlight comments for documentation in a different color
-it makes it easier to search threw documentation
-what if you're comment is not meant to go in the doc?

**Comment by ForsakenHarmony** [comment]
Rust's doc gen is pretty good, I think they use markdown as well

**Comment by yoanlcq** [comment]
A bit late to the party, but [you might really want to look at how Rust does it](https://doc.rust-lang.org/std/option/enum.Option.html).  
Just click the `[src]` button in any part of the doc to see the actual source, including their documentation comments. 

 It's Markdown, and examples in documentation are automatically tested by the compiler when running `cargo test`. Also you can insert lints enabling (or disabling) warnings about undocumented items.  
Also documentation comments (i.e with `///` for the next item or `//!` for the root item) are actually just syntactic sugar for regular metadata attributes (just like `#[inline]` and friends).

There's room for improvement, for instance referencing items such as parameters, types and modules is a bit hackish and not convenient to do. As a result most people (including me) just write them between ticks ('\`') to show that it's code, but obviously it's not satisfying.

Anyway, one should pick a solution which makes it super easy and super fun to write good-looking documentation for anything. XML is certainly not one. Markdown might be, but has its annoyances. Putting everything between ticks gets old fast, and most of the syntax is useless for documentation of code. 
Perhaps a small markup language designed for this purpose could do the trick.

**Comment by gingerBill** [comment]
I am closing this issue as it's very very old and a newer one with newer details a better idea.
