### ISSUE TITLE
Remove `opaque` type

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#762]
Remove `opaque` type:

* It has shown little practical utility
* It is confusing to most people even if they know what it does and how it works

Solutions:

* Completely remove the concept and the keyword
* Remove the keyword and make it a directive instead, i.e. `#opaque T`

**Comment by F0x1fy** [comment]
I feel the concept is useful after doing research to figure out how it works. There's no documentation to really figure out what `opaque` actually does, only mentions of its existence in the [Odin Language Specification](http://odin-lang.org/ref/spec/). It took some digging around in the Discord to get an idea of what it does. I feel that if there was a central definition with some examples, it would clear up a lot of the misunderstanding. Some people may not even know it exists due to the lack of documentation.

The idea is useful, and now that I know what it actually does, I can see uses for it. At worst, it would still be useful to have around as a directive as I could see myself using this for future libraries.
