### ISSUE TITLE
Replace `inline` and `no_inline` keywords with `#force_inline` and `#force_no_inline` directives

### ISSUE THREAD

**Issue by gingerBill** [odin-lang/Odin#764]
Replace `inline` and `no_inline` keywords with `#force_inline` and `#force_no_inline` directives.

Main rationale:

* People do not realize that `inline` and `no_inline` are __not__ hints but forced requirements
* Making it explicit it is "forced" is better than the common behaviour other languages have which is only a "hint" (and usually is completely ignored by the compiler too)

Considerations:

* `inline for` could be renamed as `#unroll for`

**Comment by F0x1fy** [comment]
I can see the argument for both sides, but personally, I think I prefer the directives. It makes more sense, as the directives, how I envision them, are more compiler-oriented rather than language-oriented. I feel the `inline` and `no_inline` keywords blur the line between the two. I would welcome this change.

**Comment by gingerBill** [comment]
I am also considering removing `inline` and `no_inline` to procedure literals and only have it on procedure _calls_
e.g.
```
foo :: inline proc() {...} // disallow

inline foo() // allow
```

**Comment by gingerBill** [comment]
Work has begun for deprecation in: https://github.com/odin-lang/Odin/commit/908a403d78c66ff306262d0983b56a0e42e0d7ed

**Comment by gingerBill** [comment]
`inline for` will be replaced with `#unroll for`
