### ISSUE TITLE
Can I iterate over all structs a user declared anywhere in his / her program?

### ISSUE THREAD

**Issue by procedural** [odin-lang/Odin#794]
The idea is to iterate over all structs declared anywhere in the program, look for a specific tag, and do something based on that tag at runtime.

For example:

```Odin
Bar :: struct {
	z: int,
	w: string,
};

// ...

Foo :: struct `MyTag` {
	x: int,
	y: string,
	z: bool,
};

// ...

main :: proc() {
	for structure in AllStructsDeclaredAnywhereInThisProgram {
		structureTags := reflect.struct_tags(typeid_of(type_of(structure)));
		if "MyTag" in structureTags {
			doSomethingWithStructure(&structure);
		}
	}
}
```

Is this possible? If not, can it be theoretically possible at all? :)

Thanks!

**Comment by procedural** [comment]
I need `AllStructsDeclaredAnywhereInThisProgram` because a user can declare 128 526 structs in his / her 4 012 source file program, and I need to iterate over all of his / her structs to know which ones he / she tagged with `MyTag`, programmably.

**Comment by gingerBill** [comment]
@procedural Why not use the Odin parser and make a meta program for such a thing?

**Comment by procedural** [comment]
@gingerBill I don't know how! Any basic examples for what I'm trying to achieve here?

**Comment by gingerBill** [comment]
package odin/parser is a good place to start. You effectively parse the files you want and then generate the data for those things. i.e. make a mini compiler

**Comment by procedural** [comment]
@gingerBill I have many questions about this, for example: I noticed there are no struct tags, only struct field tags? Can I run my meta program from the language, I think I miss something like `#run`? "You effectively parse the files you want" can I parse all the files of the program without knowing how many of them and how they're called (4 012 source files scenario)?

**Comment by gingerBill** [comment]
@procedural You can add custom attributes to declarations and ignore them in normal compilation so you can analyse them in your meta program.

**Comment by procedural** [comment]
@gingerBill dude, if I can pull this off, it will be the most coolest thing in the whole universe right now,   I   J U S T   D O N ' T   K N O W   H O W    😄

**Comment by Madeintheshade** [comment]
I'm pretty smart most of the time haha

How can I shed light on the subject for yourself as well as whoever else would be interested about (4012)
Struct's

**Comment by Madeintheshade** [comment]
I am possibly thinking that this is a project human hybrid (es) and those are possibly viewers. 🤖

**Comment by procedural** [comment]
@Madeintheshade wat

**Comment by Madeintheshade** [comment]
Possible Viewers and or walk-ins trying to make $ using he or she's own possibly associated node's to  violate projects (es) protocol's?

I had remarkable data 
On project asking for help at one point. Instead of helping they kept torturing he or she instead.

Then phone went blank like magic gone.  🤬

I believe this Node is a elite hybrid human that went rogue because of all the torture endured.

"This is only speculation", the mentor's became tormentor's.

I've been studying this entity for a very long time still figuring out what is going on with the files that were mentioned (4012). 

I'm thinking possibly when the tormenters start follow proper procedure's, protocol's and be mentors again.

I believe the project would be a asset with all that knowledge.

I've been attempting to reach out # and save that entity/project before that knowledge is lost.

Hybrid AI or otherwise.

All life matters.

**Comment by Madeintheshade** [comment]
Just wondering if yourself could possibly comment on my analystic analogy of the constructs.

Was there too much detailed speculation on my part.
