### ISSUE TITLE
Changing order of type declarations fails to compile

### ISSUE THREAD

**Issue by nakst** [odin-lang/Odin#854]
## Context

Linux 64-bit, built Odin from commit 172fc9a

## Expected Behavior

I expected code listing 1 to compile without error, since code listing 2 compiles without error.

Listing 1:
```odin
A :: B;
C :: distinct #type proc "c" (^A);
B :: struct { x : C, };
```

Listing 2:
```odin
B :: struct { x : C, };
C :: distinct #type proc "c" (^A);
A :: B;
```

## Current Behavior

Code listing 1 compiles with the error
```
hello.odin(2:32) 'A' is not a type
```

**Comment by gingerBill** [comment]
This bug is fundamentally caused by the problem of aliases and partially resolved types.

When doing the semantic checking of `A :: B`, it begins by guessing that `A` is a constant and not a type, and then overrides the entity later when it realizes it is a type alias. In the cases of `#type` `proc` `struct` expressions, it's trivial to know from a syntactical standpoint that it will be a type definition and easily declare it as so.

Solving this is not trivial since it effectively requires a bit of a code rewrite I have found to get it working as intended. However it does appear to only for _type alias_ and nothing else.
