### ISSUE TITLE
"Incorrect" output names used with `-out:` if string contains dots

### ISSUE THREAD

**Issue by oskarnp** [odin-lang/Odin#900]
Using `odin build -out:foo.debug` outputs a foo.debug executable, but temp files are named foo.ll/foo.o/foo.bc.

Same issue when using `-build-mode:asm` the resulting file is "string up to first dot" followed by .S, which is "incorrect."  (Or not in any way I would expect.)

**Comment by Kelimion** [comment]
If there's a `.` in the filename, it strips it off the extension. That's why you're seeing this.

`W:\odin-test>odin build . -out:foo.debug -keep-temp-files`
15/08/2021  23:46           321.536 foo.exe
15/08/2021  23:46         1.457.346 foo.ll
15/08/2021  23:46           300.123 foo.obj

To get the result you want, add an extension.
`W:\odin-test>odin build . -out:foo.debug.exe -keep-temp-files`
15/08/2021  23:46           321.536 foo.debug.exe
15/08/2021  23:46         1.457.357 foo.debug.ll
15/08/2021  23:46           300.123 foo.debug.obj

**Comment by ap29600** [comment]
this is very weird behaviour.

for example, this being the folder structure:
```
dir
 \-- pkg
      \-- pkg.odin
```
in `dir` running: `odin run pkg` fails because `pkg` is already a directory.
the obvious workaround would be `odin run pkg -out:pkg.bin`, which (on Linux) creates the correct executable but then fails to run it (instead, tries to execute the directory).

**Comment by ThisDrunkDane** [comment]
Yea the compiler probably shouldn't strip the extension off @gingerBill
