### ISSUE TITLE
OpenBSD port request

### ISSUE THREAD

**Issue by Scorpox59** [odin-lang/Odin#984]
Hi gingerBill,
I would like to try Odin on OpenBSD, but it doesn't compile.

clang src/main.cpp -Wno-switch -Wno-pointer-sign -Wno-tautological-constant-out-of-range-compare -Wno-tautological-compare -Wno-macro-redefined -std=c++14 -DGIT_SHA=\"\" -DODIN_VERSION_RAW=\"dev-2021-05\" -g -pthread -ldl -lm -lstdc++ -o odin
In file included from src/main.cpp:3:
In file included from src/common.cpp:19:
src/gb/gb.h:201:4: error: This UNIX operating system is not supported
                #error This UNIX operating system is not supported
                 ^
src/gb/gb.h:321:12: fatal error: 'sys/sendfile.h' file not found
                #include <sys/sendfile.h>
                         ^~~~~~~~~~~~~~~~

**Comment by Platin21** [comment]
There was once a pull request for this you might want to take a look at that.

**Comment by krixano** [comment]
I got FreeBSD done, and I was working on NetBSD but never finished it. I can't remember everything that I did for FreeBSD, but I think you need to add defines, you might have to change the src/gb/gb.h file. You will also need to add targets to src/build_settings.cpp, I think. And then add support to the core library (which required looking up how some things are defined in FreeBSD).

Although, much of this work for FreeBSD was done *prior* to the new backend, so I'm not sure what has changed - I'm not even sure if FreeBSD works anymore since the switch :D 
But you can see what I did for FreeBSD Here: https://github.com/odin-lang/Odin/pull/734
